site_name: Markdown-Notes
theme:
  name: material
nav:
  - Home: index.md
  - Getting Started:
      - Intro: getting-started/intro.md
      - Setup: getting-started/setup.md
  - Guides:
      - Usage: guides/usage.md
      - FAQ: guides/faq.md
