site_name: MD-Notes
theme:
  name: material
  font:
    code: Roboto Mono
nav:
  - Home: index.md
  - About: about.md
  - Installation: installation.md
  - Usage: usage.md
  - Design Pattern:
      - Overview: Design-Pattern/index.md
  - Reference:
      - API: reference/api.md
      - Configuration: reference/config.md

extra_css:
  - 'stylesheets/custom.css'  # Optional: for custom styles

extra_javascript:
  - 'javascripts/custom.js'   # Optional: for custom scripts
